package net.astrorbits.dontdoit.criteria.system

enum class CriteriaType {
    EAT_ITEM,
    DROP_ITEM,
    CRAFT_ITEM,
    PICK_UP_ITEM,
    HOLDING_ITEM,

    WALK_DISTANCE,
    JUMP,
    FALL_DISTANCE,

    BREAK_BLOCK,
    PLACE_BLOCK,
    INTERACT_BLOCK_WITH_ITEM,

    HURT_ENTITY,
    KILL_ENTITY,
    HURT_BY_ENTITY,
    KILLED_BY_ENTITY,

    HEALTH,
    ROTATION,
    FOOD_LEVEL,
    SURROUNDED_BY_BLOCK,
    STANDING_ON_BLOCK,
    DISTANCE_TO_ENTITY,
    HEIGHTMAP_MATCHING_POS,
    INVENTORY_CONTAINING_ITEM,

    RESPAWN_TIME,
    MOVE_TIME
}
