package net.astrorbits.dontdoit.criteria.helper

enum class CriteriaType {
    // 物品相关
    EAT_ITEM,
    USE_TOOL,
    DROP_ITEM,
    CRAFT_ITEM,
    PICK_UP_ITEM,
    HOLDING_ITEM,
    TRANSFER_ITEM,
    INVENTORY_CONTAINING_ITEM,

    // 方块相关
    BREAK_BLOCK,
    PLACE_BLOCK,
    OPEN_INVENTORY,
    PHYSICAL_ACTION,
    INTERACT_BLOCK_WITH_ITEM,
    SURROUNDED_BY_BLOCK,
    IN_BLOCK,
    STANDING_ON_BLOCK,
    BUCKET_OPERATION,

    // 实体相关
    STATUS_EFFECT,
    HURT_ENTITY,
    KILL_ENTITY,
    HURT_BY_ENTITY,
    KILLED_BY_ENTITY,
    DISTANCE_TO_ENTITY,

    // 时间相关
    RESPAWN_TIME,
    MOVE_TIME,
    CRITERIA_HOLD_TIME,
    AFTER_DEATH_TIME,

    // 杂项
    CHAT,
    HEALTH,
    ROTATION,
    FOOD_LEVEL,
    SELECTED_HOTBAR_SLOT,
    HEIGHTMAP_MATCHING_POS,
    LIFE_COUNT,
    WALK_DISTANCE,
    JUMP,
    FALL_DISTANCE,
    LEVEL_UP,
    IMMEDIATELY_TRIGGER,

    // 内建类型
    Y_LEVEL,
    USER_DEFINED
}
