package net.astrorbits.dontdoit.criteria

enum class CriteriaType {
    EAT_ITEM,
    DROP_ITEM,
    CRAFT_ITEM,
    PICK_UP_ITEM,
    HOLDING_ITEM,

    WALK,
    JUMP,
    FALL,

    BREAK_BLOCK,
    PLACE_BLOCK,
    INTERACT_WITH_BLOCK_HOLDING_ITEM,

    HURT_ENTITY,
    KILL_ENTITY,
    HURT_BY_ENTITY,
    KILL_BY_ENTITY,

    HEALTH,
    Rotation,
    FOOD_LEVEL,
    STANDING_ON_BLOCK,
    DISTANCE_TO_ENTITY,
    HEIGHTMAP_MATCHING_POS,
    INVENTORY_CONTAINING_ITEM
}
